# Generated by Django 2.1.3 on 2018-12-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20181228_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
