# Generated by Django 2.1.3 on 2018-11-23 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0005_stripeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deliv_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('deliv_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('deliverer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to=settings.AUTH_USER_MODEL)),
                ('orderer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.Store')),
            ],
        ),
    ]
